[cqc]
api_key = "YOUR_CQC_API_KEY"

[companies_house]
api_key = "YOUR_COMPANIES_HOUSE_API_KEY"

[auth]
# Example credentials for streamlit-authenticator
# Replace with hashed passwords if using
usernames = ["demo"]
passwords = ["demo"]
